language: bash
services: docker

env:
  - VARIANT=debian
  - VARIANT=alpine
  - VARIANT=ubuntu

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="memcached:$VARIANT"

script:
  - travis_retry docker build -t "$image" "$VARIANT"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
